const swaggerAutogen = require("swagger-autogen")();

const outputFile = "./swagger_output.json";
const endpointsFiles = [
  "./app/routes/user.routes.js",
  "./app/routes/animal.routes.js",
  "./app/routes/auth.routes.js",
];

const doc = {
  info: {
    version: "1.0.0",
    title: "Znuffy API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:8080",
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "User",
      description: "Endpoints",
    },
  ],
  securityDefinitions: {
    api_key: {
      type: "apiKey",
      name: "api_key",
      in: "header",
    },
    petstore_auth: {
      type: "oauth2",
      authorizationUrl: "https://petstore.swagger.io/oauth/authorize",
      flow: "implicit",
      scopes: {
        read_pets: "read your pets",
        write_pets: "modify pets in your account",
      },
    },
  },
  definitions: {
    // User
    User: {
      username: "Jhon Doe",
      email: "JhonDoe@jhondoe.com",
      password: "1234567890",
      posts: ["62c067dd6ebb54f2e2c8d2e9", "62c069d3a2af80019993eeb1"],
      roles: [
        "62b877546bd60837b8d82c6b",
        "62b877546bd60837b8d82c6c",
        "62b877546bd60837b8d82c6d",
      ],
    },
    // Post Animal for adoption
    AddUser: {
      type: "Cat",
      name: "Miauchi",
      location: "Rosalia de las Adas 372, Asuncion, Paraguay",
      age: 2,
      genre: "Female",
      breed: "Stray",
      characteristics: {
        easyToGrood: false,
        dogFriendly: true,
        catFriendly: false,
        houseTrained: false,
        leashTrained: false,
        goodWithKids: false,
        energyLevel: 5,
        vocality: 5,
      },
      medicalInfo: {
        vaccinated: true,
        neutured: true,
        shortHair: true,
        allergyFriendly: true,
        diaryRestrictions: false,
        needsMedication: false,
        disability: false,
        spayed: false,
      },
      story:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      poster: {
        id: "62c05b6fe854ed618fd2a607",
        number: 595994880781,
      },
    },
  },
};

swaggerAutogen(outputFile, endpointsFiles);

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("./server.js");
});
